-- ============================================================
-- SnapClass — AI Attendance
-- Supabase / PostgreSQL Database Schema
-- ============================================================
--
-- This schema matches the current application's database access
-- layer in src/db.py.
--
-- Security policies (RLS) are intentionally handled separately
-- as part of the security phase.
-- ============================================================


-- ============================================================
-- 1. TEACHERS
-- ============================================================

create table if not exists public.teachers (
    teacher_id bigint generated by default as identity primary key,
    username text not null unique,
    password text not null,
    name text not null,
    created_at timestamptz not null default now()
);


-- ============================================================
-- 2. STUDENTS
-- ============================================================

create table if not exists public.students (
    student_id bigint generated by default as identity primary key,
    name text not null,

    -- 128-dimensional dlib face embedding.
    -- Stored as JSON so it can be converted back to a NumPy array.
    face_embedding jsonb not null,

    -- Resemblyzer speaker embedding.
    -- Nullable because voice registration is optional.
    voice_embedding jsonb,

    created_at timestamptz not null default now()
);


-- ============================================================
-- 3. SUBJECTS / CLASSES
-- ============================================================

create table if not exists public.subjects (
    subject_id bigint generated by default as identity primary key,

    subject_code text not null,
    name text not null,
    section text not null,

    teacher_id bigint not null
        references public.teachers(teacher_id)
        on delete cascade,

    created_at timestamptz not null default now()
);


-- ============================================================
-- 4. STUDENT ↔ SUBJECT ENROLLMENTS
-- ============================================================

create table if not exists public.subject_students (
    student_id bigint not null
        references public.students(student_id)
        on delete cascade,

    subject_id bigint not null
        references public.subjects(subject_id)
        on delete cascade,

    created_at timestamptz not null default now(),

    primary key (student_id, subject_id)
);


-- ============================================================
-- 5. ATTENDANCE LOGS
-- ============================================================

create table if not exists public.attendance_logs (
    attendance_id bigint generated by default as identity primary key,

    student_id bigint not null
        references public.students(student_id)
        on delete cascade,

    subject_id bigint not null
        references public.subjects(subject_id)
        on delete cascade,

    timestamp timestamptz not null default now(),

    is_present boolean not null default false
);


-- ============================================================
-- INDEXES
-- ============================================================

-- Teacher → subjects
create index if not exists idx_subjects_teacher_id
    on public.subjects(teacher_id);


-- Subject → enrolled students
create index if not exists idx_subject_students_subject_id
    on public.subject_students(subject_id);


-- Student → enrolled subjects
create index if not exists idx_subject_students_student_id
    on public.subject_students(student_id);


-- Student → attendance records
create index if not exists idx_attendance_logs_student_id
    on public.attendance_logs(student_id);


-- Subject → attendance records
create index if not exists idx_attendance_logs_subject_id
    on public.attendance_logs(subject_id);


-- Timestamp-based attendance queries
create index if not exists idx_attendance_logs_timestamp
    on public.attendance_logs(timestamp);


-- ============================================================
-- NOTES
-- ============================================================
--
-- 1. Teacher passwords are hashed using bcrypt in the
--    application before being inserted.
--
-- 2. Face embeddings are generated by dlib and contain
--    128 floating-point values.
--
-- 3. Voice embeddings are generated by Resemblyzer and
--    stored as JSON-compatible arrays.
--
-- 4. A student can be enrolled in many subjects.
--
-- 5. A subject can contain many students.
--
-- 6. Attendance records connect students with subjects.
--
-- 7. Row Level Security (RLS) policies should be added
--    during the security phase of the project.
--
-- ============================================================